#!/bin/sh
/usr/bin/java -Dzookeeper.log.dir=/var/log/zookeeper -Dzookeeper.root.logger=INFO,ROLLINGFILE -cp /usr/lib/zookeeper/bin/../build/classes:/usr/lib/zookeeper/bin/../build/lib/*.jar:/usr/lib/zookeeper/bin/../zookeeper-3.3.5-cdh3u4.jar:/usr/lib/zookeeper/bin/../lib/log4j-1.2.15.jar:/usr/lib/zookeeper/bin/../lib/jline-0.9.94.jar:/usr/lib/zookeeper/bin/../src/java/lib/*.jar:/etc/zookeeper::/etc/zookeeper:/usr/lib/zookeeper/*:/usr/lib/zookeeper/lib/* -Dzookeeper.log.threshold=INFO -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.PurgeTxnLog /var/zookeeper /var/zookeeper -n 3

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t zookeeper-PurgeTxnLog "ALERT exited abnormally with [$EXITVALUE]"
    fi
exit 0
